import crypto from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const dist = path.join(root, 'dist');
const packageJson = JSON.parse(fs.readFileSync(path.join(root, 'package.json'), 'utf8'));

if (!fs.existsSync(dist)) {
  throw new Error('dist/ does not exist. Run Vite before generating offline support.');
}

function walk(directory) {
  return fs.readdirSync(directory, { withFileTypes: true })
    .flatMap((entry) => {
      const absolute = path.join(directory, entry.name);
      if (entry.isDirectory()) return walk(absolute);
      return entry.isFile() ? [absolute] : [];
    });
}

const files = walk(dist)
  .filter((absolute) => path.basename(absolute) !== 'service-worker.js')
  .map((absolute) => path.relative(dist, absolute).split(path.sep).join('/'))
  .sort();

if (!files.includes('index.html')) throw new Error('dist/index.html is missing.');
if (!files.includes('manifest.webmanifest')) throw new Error('dist/manifest.webmanifest is missing.');

const fingerprint = crypto.createHash('sha256');
for (const relative of files) {
  const absolute = path.join(dist, ...relative.split('/'));
  fingerprint.update(relative);
  fingerprint.update('\0');
  fingerprint.update(fs.readFileSync(absolute));
  fingerprint.update('\0');
}
const revision = fingerprint.digest('hex').slice(0, 16);
const cacheName = `ispy-offline-${packageJson.version}-${revision}`;
const paths = files.map((relative) => `./${encodeURI(relative)}`);

const worker = `/* Generated by scripts/build-pwa.mjs. Do not edit dist/service-worker.js by hand. */
const CACHE_PREFIX = 'ispy-offline-';
const CACHE_NAME = ${JSON.stringify(cacheName)};
const PRECACHE_PATHS = ${JSON.stringify(paths, null, 2)};
const INDEX_URL = new URL('./index.html', self.registration.scope).href;

function scopedUrl(relativePath) {
  return new URL(relativePath, self.registration.scope).href;
}

self.addEventListener('install', (event) => {
  event.waitUntil((async () => {
    const cache = await caches.open(CACHE_NAME);
    await cache.addAll(PRECACHE_PATHS.map(scopedUrl));
    await self.skipWaiting();
  })());
});

self.addEventListener('activate', (event) => {
  event.waitUntil((async () => {
    const names = await caches.keys();
    await Promise.all(names
      .filter((name) => name.startsWith(CACHE_PREFIX) && name !== CACHE_NAME)
      .map((name) => caches.delete(name)));
    await self.clients.claim();
  })());
});

function rangeNotSatisfiable(size) {
  return new Response(null, {
    status: 416,
    headers: { 'Content-Range': 'bytes */' + size },
  });
}

async function rangedResponse(request, cached) {
  const rangeHeader = request.headers.get('range');
  if (!rangeHeader) return cached;

  const match = /^bytes=(\\d*)-(\\d*)$/i.exec(rangeHeader.trim());
  if (!match) return cached;

  const bytes = await cached.arrayBuffer();
  const size = bytes.byteLength;
  let start;
  let end;

  if (match[1] === '') {
    const suffixLength = Number(match[2]);
    if (!Number.isFinite(suffixLength) || suffixLength <= 0) return rangeNotSatisfiable(size);
    start = Math.max(0, size - suffixLength);
    end = size - 1;
  } else {
    start = Number(match[1]);
    end = match[2] === '' ? size - 1 : Number(match[2]);
  }

  if (!Number.isFinite(start) || !Number.isFinite(end) || start < 0 || start >= size || end < start) {
    return rangeNotSatisfiable(size);
  }

  end = Math.min(end, size - 1);
  const chunk = bytes.slice(start, end + 1);
  const headers = new Headers();
  const contentType = cached.headers.get('content-type');
  if (contentType) headers.set('Content-Type', contentType);
  headers.set('Accept-Ranges', 'bytes');
  headers.set('Content-Range', 'bytes ' + start + '-' + end + '/' + size);
  headers.set('Content-Length', String(chunk.byteLength));

  return new Response(chunk, {
    status: 206,
    statusText: 'Partial Content',
    headers,
  });
}

async function cacheFirst(request) {
  const cached = await caches.match(request);
  if (cached) return rangedResponse(request, cached);

  const response = await fetch(request);
  if (response && response.ok && new URL(request.url).origin === self.location.origin) {
    const cache = await caches.open(CACHE_NAME);
    cache.put(request, response.clone()).catch(() => {});
  }
  return response;
}

async function navigationResponse(request) {
  try {
    return await fetch(request);
  } catch {
    const cache = await caches.open(CACHE_NAME);
    return (await cache.match(INDEX_URL)) || Response.error();
  }
}

self.addEventListener('fetch', (event) => {
  const request = event.request;
  if (request.method !== 'GET') return;

  const url = new URL(request.url);
  if (url.origin !== self.location.origin) return;

  if (request.mode === 'navigate') {
    event.respondWith(navigationResponse(request));
    return;
  }

  event.respondWith(cacheFirst(request));
});
`;

fs.writeFileSync(path.join(dist, 'service-worker.js'), worker);
console.log(`I SPY PWA generated: ${files.length} precached files -> ${cacheName}`);
